curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('',views.CourseListView,name='course_list'),
    path('<course_id>/', views.SubjectsView ,name='subjects-list'),
    path('<course_id>/lesson/<subject_id>/', views.LessonsView , name='lessons-list'),
    path('<course_id>/<subject_id>/add/', views.LessonCreateView,name='create'),
    path('subject/<subject_id>/<lesson_id>/',views.LessonDetailView,name='lesson-detail'),
    path('<subject_id>/<lesson_id>/update/',views.LessonUpdateView,name='lesson-update'),
    path('lesson/<int:pk>/delete/',views.LessonDeleteView.as_view(),name='lesson-delete'),
    path('1/api/courses/',views.CourseView.as_view()),
    path('1/api/subjects/',views.SubjectsApiView.as_view()),
    path('1/api/lessons/',views.LessonView.as_view()),
    path('1/<course_id>/payment/', views.payment, name='payment'),
    path('<course_id>/<order_id>/',views.Order),
    path('1/api/course_paid/',views.CoursePaidApiView.as_view()),

]

istudy_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('istudy_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

curriculum/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from istudy_users.models import User
import os
from mptt.models import MPTTModel , TreeForeignKey

# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=200,unique=True)
    description = models.TextField(max_length=500,blank=True)
    def __str__(self):
        return self.name

class CoursePayment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,blank=True)
    order_id=models.CharField(null=True,blank=True,max_length=40)
    paid = models.BooleanField(default=False)


    def __str__(self):
        return self.course.name 

class Subject(models.Model):
    name = models.CharField(max_length=200)
    course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='subjects')
    image= CloudinaryField('image',null=True,blank=True)
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    
def save_lesson_files(instance,filename):
    upload_to ='Images/'
    ext = filename.split('.')[-1]

    if instance.lesson_id:
        filename = 'lesson_files/{}/{}.{}'.format(instance.lesson_id,instance.lesson_id,ext)

        if os.path.exists(filename):
            new_name = str(instance.lesson_id)+ str('1')
            filename = 'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name,ext)

    return os.path.join(upload_to,filename)
        


class Lesson(models.Model):
    lesson_id = models.CharField(max_length=100,unique=True)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,related_name='lessons')
    name = models.CharField(max_length=300)
    position = models.PositiveSmallIntegerField(verbose_name='Chapter no.')
    video= models.FileField(upload_to=save_lesson_files,verbose_name='Video',blank=True,null=True)
    ppt = models.FileField(upload_to=save_lesson_files,verbose_name='Presentation',blank=True)
    notes = models.FileField(upload_to=save_lesson_files,verbose_name='Notes',blank=True)

    class Meta:
        ordering = ['position']

    


    def __str__(self):
        return self.name

    
class Comment(MPTTModel):
    lesson = models.ForeignKey(Lesson,null=True, on_delete=models.CASCADE,related_name='comments')
    parent = TreeForeignKey('self', on_delete=models.CASCADE,null=True, blank=True, related_name='children')
    author = models.ForeignKey(User,null=True, on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    publish= models.DateTimeField(auto_now_add=True)


    
    def __str__(self):
        return f'Comment by {self.author}'
    class MPTTMeta:
        order_insertion_by = ['publish']
 

curriculum/forms.py
from django import forms
from .models import Lesson,User,Comment
from mptt.forms import TreeNodeChoiceField
from cloudinary.forms import CloudinaryFileField


class LessonForm(forms.ModelForm):
   
   
    class Meta:
        model = Lesson
        fields = ('__all__')
        exclude = ['created_by','course','subject']

class LessonUpdateForm(forms.ModelForm):
    class Meta:
        model =Lesson
        fields = ('__all__')
        exclude = ['created_by','course','subject']

class CommentForm(forms.ModelForm):
    parent=TreeNodeChoiceField(queryset=Comment.objects.all())
    

    def __init__(self,*args, **kwargs):
        super().__init__(*args,**kwargs)


        self.fields['parent'].widget.attrs.update(
            {'class':'d-none'})
        self.fields['parent'].label = ''

        self.fields['parent'].required=False
        
    class Meta:
        model = Comment
        labels = {"content":"Comment:"}
        widgets = {
            'content': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }
        fields = ('author','content','parent')
        exclude = ['author']


        

curriculum/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import *
from .models import Course, Subject, Lesson,Comment,CoursePayment
from django.urls import reverse_lazy
from .forms import LessonForm,LessonUpdateForm,CommentForm
from django.http import HttpResponseRedirect,FileResponse
from django.views.generic import DeleteView
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic.base import TemplateView
from django.conf import settings
import random

def CourseListView(request):
  courses = Course.objects.all()
  return render(request,'course_list.html',{"courses":courses})

def SubjectsView(request,course_id):
  course=Course.objects.get(id=course_id)
  subjects = Subject.objects.filter(course=course)
  return render(request,'subject.html',{"course":course,"subjects":subjects})

def payment(request,course_id):
  course=Course.objects.get(id=course_id)
  current_user = request.user
  course_payment = CoursePayment.objects.filter(user=current_user,course=course).first()
  if course_payment:
    return redirect('curriculum:subjects-list',course.id)

  subjects = Subject.objects.filter(course=course)
  public_key = settings.RAVE_PUBLIC_KEY
  random_num =  random.randint(2345678909800, 9923456789000)

  return render(request,'payment.html',{"course":course,"subjects":subjects,'public_key':public_key,'current_user':current_user,'random_num':random_num})

def LessonsView(request,course_id,subject_id):
  course=Course.objects.get(id=course_id)
  subject=Subject.objects.filter(id=subject_id).first()
  lessons=Lesson.objects.filter(subject=subject)
  return render(request,'lesson.html',{"course":course,"subjects":subject,"lessons":lessons})


def LessonDetailView(request,subject_id,lesson_id):
  subject=Subject.objects.get(id=subject_id)
  lesson=Lesson.objects.get(id=lesson_id)
  allcomments= Comment.objects.filter(lesson=lesson).order_by('id')
  page = request.GET.get('page',1)
  paginator = Paginator (allcomments,3)

  try:
    comments = paginator.page(page)
  except PageNotAnInteger:
    comments = paginator.page(1)
  except EmptyPage:
    comments = paginator.page(paginator.num_pages)


  user_comment = None
  if request.method == 'POST':
    comment_form = CommentForm(request.POST,request.FILES or None)
    if comment_form.is_valid():
      user_comment = comment_form.save(commit=False)
      user_comment.lesson = lesson
      user_comment.author = request.user
      user_comment.save()
      return redirect('curriculum:lesson-detail',subject.id,lesson.id)
  else:
    comment_form = CommentForm()

  return render(request,'lesson_details.html',{"subject":subject,"lesson":lesson,'comment_form':comment_form,'comments':comments,'allcomments': allcomments,})

def LessonCreateView(request,course_id,subject_id):
  course= Course.objects.get(id=course_id)
  subject=Subject.objects.get(id=subject_id)
  lesson = Lesson.objects.filter(subject=subject)
  if request.method == 'POST':
    form = LessonForm(request.POST, request.FILES)
    if form.is_valid():
      create= form.save(commit=False)
      create.created_by =request.user
      create.course = course
      create.lesson=lesson
      create.subject = subject
      create.save()
      return redirect('curriculum:lessons-list',course.id,subject.id)
  else:
    form = LessonForm()
  return render(request,'lesson_create.html',{'form':form,'lesson':lesson,"subject":subject,'course':course})


def LessonUpdateView(request,subject_id,lesson_id):
  subject=Subject.objects.get(id=subject_id)
  lesson=Lesson.objects.get(id=lesson_id)

  if request.method == 'POST':
    form = LessonUpdateForm(request.POST,request.FILES,instance=lesson)
    if form.is_valid():
      form.save()
      return redirect('curriculum:lesson-detail',subject.id,lesson.id)
  
  else:
    form= LessonUpdateForm(instance=lesson)
  return render(request,'lesson_update.html',{"subject":subject,"lesson":lesson,'form':form})

class LessonDeleteView(DeleteView):
  model = Lesson
  template_name = "lesson_delete.html"


  def get_success_url(self):
        return reverse_lazy('curriculum:course_list')



class CourseView(APIView):
  def get(self,request):
    courses=Course.objects.all()
    serializer=CourseSerializer(courses,many=True)
    return Response(serializer.data)

  def post(self):
    pass 

class SubjectsApiView(APIView):
  def get(self,request):
    subjects=Subject.objects.all()
    serializer=SubjectSerializer(subjects,many=True)
    return Response(serializer.data)

  def post(self):
    pass 

class LessonView(APIView):
  def get(self,request):
    lessons=Lesson.objects.all()
    serializer=LessonSerializer(lessons,many=True)
    return Response(serializer.data)

  def post(self):
    pass 


class HomePageView(TemplateView):
    template_name = 'subject.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.RAVE_PUBLIC_KEY
        return context


def Order(request,course_id,order_id):
  print(course_id)

  course = Course.objects.filter(pk=course_id).first()
  current_user = request.user
  course_payment = CoursePayment(user=current_user,course=course,order_id=str(order_id),paid=True)
  course_payment.save()
  return redirect('curriculum:subjects-list', course.id)


class CoursePaidApiView(APIView):
  def get(self,request):
    course_paid=CoursePayment.objects.all()
    serializer= CoursePaidSerializer(course_paid,many=True)
    return Response(serializer.data)

  def post(self):
    pass 

curriculum/templates/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Courses {% endblock %}

{% block content %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 "
          style="color:#76B947;font-family: 'Atma', cursive;letter-spacing: 4px;"> Curriculum</h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb" style="font-family: 'Source Code Pro', monospace;">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li class="disabled-text">Curriculum</li>


          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#76B947;">

        <!-- description -->
        <!-- <h4 class="white-text my-4">“The more that you read, the more things you will know. The more that you learn, the more places you’ll go.” – Dr.  Seus</h4> -->
      </div>
</header>
<!-- section 1 for courses-->
<div class="jumbotron jumbotron-fluid text-center bg-gray">
  <h2 class="font-weight-bold" style="color:#76B947;font-family: 'Source Code Pro', monospace;">Explore our
    curriculum</h2>
  <!-- class row for description-->
  <div class="row d-flex justify-content-center">
    <!-- class column -->
    <div class="col-md-8">
      <p class="grey-text" style="font-size: 20px;">Istudy is an online learning tool for kids from Kindergarden to
        Grade 3 three. The lessons and materials
        provided are based on the class. Find the one suitable for your kid, and start enjoying learning with us!
    </div>
  </div>
</div>
<section id="best-features" class="text-center">


  <!-- class row2 for cards -->
  <div class="row ml-2 mr-2">
    {% for course in courses %}
    <div class="col-md-3 d-flex mb-5 justify-content-center">
      <div class="card card-std text-center" style="width: 20rem;">
        <div class="card-body text-center">
          <h4 class="card-title"
            style="color:#fff;font-family: 'Atma', cursive;letter-spacing: 4px;font-weight: bolder;"><i
              class="fas fa-child"></i>&nbsp;{{course.name}}</h4>
          <p class="card-text">{{course.description|truncatechars:75}}</p>

          {% if user.is_authenticated%}
            {% if user.role == 'teacher' or user.is_superuser %}
          <a href="{% url 'curriculum:subjects-list' course.id %}" class="btn btn-warning"
            style="font-family: 'Source Code Pro', monospace;">Let's get started</a>
            {%else%}
            <a href="{% url 'curriculum:payment' course.id %}" class="btn btn-warning"
              style="font-family: 'Source Code Pro', monospace;">Let's get started</a>
  
            {%endif%}
            {%else%}
            <a href="{% url 'login' %}" class="btn btn-warning">Login</a>
          {%endif%}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>


{%endblock%}

curriculum/templates/lesson.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block content %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-12 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 "
          style="color:#76B947;font-family: 'Atma', cursive;letter-spacing: 4px;">
          Lessons</h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb" style="font-family: 'Source Code Pro', monospace;">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:course_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subjects-list' course.id %}">Subjects</a></li>
            <li class="disabled-text">Lessons</li>




          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#76B947;">

        <!-- description -->
        <!-- <h4 class="white-text my-4">“That is what learning is. You suddenly understand something you’ve understood all your life, but in a new way.” – Doris Lessing</h4> -->
      </div>
</header>
<section id="best-features" class="text-center">
  <h2 class="mb-5 mt-5 font-weight-bold" style="color:#76B947;font-family: 'Atma', cursive;letter-spacing: 4px;">Dive
    Deeper</h2>
  <!-- class row for description-->
  <div class="row d-flex justify-content-center mb-4">
    <!-- class column -->
    <!-- <div class="col-md-8 mb-5">
      <p class="grey-text">{{subjects.description}}</p>
    </div> -->
  </div>
  <!-- class row2 for cards -->
  {% for lesson in lessons %}

  <div class="row d-flex justify-content-center mb-3">

    <div class="col-sm-4 mb-4">
      <div class="card box-shadow-hover" style="max-width: 500px;background-color:#8ccc5e;color: #fff;">
        <div class="card-body">
          <h5 class="card-title" style="color:#fff;font-family: 'Atma', cursive;letter-spacing: 4px;font-weight: bolder;"><i class="fas fa-book-open"></i>&nbsp;Chapter-{{lesson.position}}: {{lesson.name}}</h5>
          <a href="{% url 'curriculum:lesson-detail' subject_id=lesson.subject.id lesson_id=lesson.id %}">
            <button type="button" class="button-les"><span>Get Lectures</span></button>
          </a>

        </div>
      </div>
    </div>
  </div>
 
  {% endfor %}
  <div class="row d-flex justify-content-center mb-3">
    {% if user.role == 'teacher' or user.is_superuser %}
     <a href="{% url 'curriculum:create' course_id=course.id subject_id=subjects.id %}" class="btn btn-success btn-lg btn-bloc"> Add new Lesson </a>
    {% endif %}
  </div>
 
</section>






{%endblock%}

curriculum/templates/lesson_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Lesson Create {% endblock %}

{% block image_block %}

{% endblock %}

{% block content %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#76B947;" > Lesson Creation </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:course_list' %}">Curriculum</a></li>
            <li class="disabled-text" >Lesson Create</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#76B947;">

        <!-- description -->
        <!-- <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4> -->
  </div>
</header>
<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#76B947;">Create a Lesson</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">“Those people who develop the ability to continuously acquire new and better forms of knowledge that they can apply to their work and to their lives will be the movers and shakers in our society for the indefinite future.” – Brain Tracy</p>
                </div>
              </div>
</section>

<div class="container mb-5">
  <div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
      <div class="card box-shadow-hover text-center">
        <div class="card-body" style="font-family: 'Source Code Pro', monospace;">
          <form method="post" enctype="multipart/form-data">
            <div class="form-group">
            {% csrf_token %}
            {{form.as_p}}
            <input class="btn btn-success btn-lg btn-block " type="submit" value="Create">
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-lg-3"></div>

  </div>
  
</div>


{% endblock %}

curriculum/templates/lesson_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %} {{lesson.name}} {% endblock %}


{% block content %}
<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
    }

    .children .children form {
      margin-left: -96px;
    }
  }

  .card {
    background: #8ccc5e;
    color: #fff;

  }

  .card-title {
    color: #fff;
    font-family: 'Atma', cursive;
    letter-spacing: 4px;
    font-weight: bolder;
  }

  .card-1 {
    background: #b0ec85;
    color: #fff;
    font-weight: bold;
  }

  .card-2 {
    background: #d4f0c6;
    font-weight: bold;
    color: black;
  }
</style>

<section class="text-center">
  <h2 class="mb-0 mt-5 font-weight-bold" style="color:#76B947;font-family: 'Source Code Pro', monospace;">Lecture
    Details</h2>
  <div class="row d-flex justify-content-center mb-3">
    <blockquote class="blockquote mt-0">
      <footer class="blockquote-footer">Created on {{lesson.created_at}} by <cite
          title="Source Title">{{lesson.created_by}}</cite></footer>
    </blockquote>
  </div>
  <!-- video -->

  <div class="row d-flex justify-content-center mb-3">
    <div id="player-overlay">
      {% if lesson.video.url %}

      <video controls>
        <source src="{{lesson.video.url}}" type="video/mp4">
      </video>

      {% else %}
      <video controls>
      <source src="#" type="video/mp4">
      </video>
      {%endif%}

    </div>
  </div>

  <!-- download cards -->
  <h3 class="mb-5 mt-5 font-weight-bold" style="color:#76B947;font-family: 'Atma', cursive;letter-spacing: 4px;">Master
    your lesson</h3>

  <div class="row d-flex justify-content-center mb-3 mt-3 ml-3 mr-3"
    style='border:1px solid grey; border-radius:20px; background-color: rgb(252, 245, 245);'>
    <!-- download presentations -->
    <div class="col-md-4 mb-4 mt-4">
      <div class="card box-shadow-hover">
        <div class="card-body">
          <h5 class="card-title">Download Presentations</h5>
          {% if lesson.ppt %}
          <p class="card-text">Download presentations from the lecture</p>
          <a href="{{lesson.ppt.url}}" download>
            <button type="button" class="button-les"><span>Get Files</span></button>
          </a>
          {% else %}
          <p class="card-text"> No PPT available</p>
          {% endif %}

        </div>
      </div>
    </div>
    <!-- download notes -->
    <div class="col-md-4 mb-4 mt-4">
      <div class="card box-shadow-hover">
        <div class="card-body">
          <h5 class="card-title">View or Notes</h5>
          {% if lesson.notes %}
          <p class="card-text">View notes from the lecture</p>
          <a href="{{lesson.notes.url}}">
            <button type="button" class="button-les"><span>My notes</span></button>
          </a>

          {% else %}
          <p class="card-text">Notes not available</p>
          {%endif%}

        </div>
      </div>
    </div>
    <!-- download video -->
    <div class="col-md-4 mb-4 mt-4">
      <div class="card box-shadow-hover">
        <div class="card-body">
          <h5 class="card-title">Download Video</h5>
          <p class="card-text">Download Video from the lecture</p>
          {% if lesson.video.url %}

          <a href="{{lesson.video.url}}" download>
            <button type="button" class="button-les"><span>Get Video</span></button>

          </a>
          {% else %}
          <p class="card-text">No video available</p>
          {%endif%}
        </div>
      </div>
    </div>
    <!-- update and delete button -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
      {% if user.role == 'teacher' or user.is_superuser %}
      <div class="col-md-6 mb-3 text-center">
        <a href="{% url 'curriculum:lesson-update' subject_id=subject.id lesson_id=lesson.id %}"
          class="btn btn-warning btn-lg mr-4 btn-block">Update Lesson</a>
      </div>
      <div class="col-md-6">
        <a href="{% url 'curriculum:lesson-delete' lesson.id %}" class="btn btn-danger btn-lg mr-4 btn-block"> Delete
          Lesson </a>
      </div>
      {% endif %}
    </div>
  </div>

</section>

<h3 class="mb-5 mt-5 font-weight-bold text-center"
  style="color:#76B947;font-family: 'Atma', cursive;letter-spacing: 4px;">Leave a comment</h3>

<div class="container">
  <div class="row justify-content-md-center pt-5">
    <div class="col-md-7">
      {% with allcomments.count as total_comments %}
      <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
      </h2>
      {% endwith %}
      {% load mptt_tags %}
      <div>
        {% recursetree comments %}
        <div id="{{ node.id }}" class="my-2 p-2"
          style="border: 1px solid grey; box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);border-radius: 20px;">
          <div class="font-weight-bold">
            <img
              src="https://res.cloudinary.com/ucynthy12/image/upload/v1609854539/421-4212275_transparent-default-avatar-png-avatar-img-png-download_cgxfx9.png"
              alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:30px;">
            By {{ node.author }}<div class="float-right">{{ node.publish }}</div>
          </div>
          <div class="mt-2 ml-5">{{ node.content }}</div>

          <hr>
          {% if node.level < 3 %} <button class="btn btn-warning" onclick="myFunction({{node.id}})">Reply</button>

            {%endif%}
        </div>
        {% if not node.is_leaf_node %}
        <div class="children pl-2 pl-md-5">
          {{children}}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>
      <div class="py-4">
        <nav aria-label="Page navigation example">
          {% if comments.has_other_pages %}
          <ul class="pagination">
            {% if comments.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for num in comments.paginator.page_range %}
            {% if comments.number == l %}
            <li class="page-item active"><span class="page-link">{{ num }} <span class="sr-only">(current)</span></span>
            </li>
            {% else %}
            <li><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
            {% if comments.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ comments.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </div>

      <hr style="color:#76B947;">

      <h2 style="color:#76B947;font-family: 'Source Code Pro', monospace;">Make a new comment</h2>

      <div class="card card-1">
        <div class="card-body">
          <form id="myForm" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning btn-lg btn-block">Submit</button>
          </form>
        </div>
      </div>



    </div>
  </div>

</div>

<script>

  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {

    if (document.contains(document.getElementById('newForm'))) {
      document.getElementById('newForm').remove()
    }
    var a = document.getElementById(id);

    a.insertAdjacentHTML('afterend', '<div class="card card-2" id="newForm" ><div class="card-body"><form class="form-insert py-2" method="post"> \
                <div class="d-flex justify-content-between"><h2>Reply:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Close</button></div></div> \
                \
                <select name="parent" class="d-none" id="id_parent"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select>  \<label for="id_content">Comment:</label> \
                <textarea name="content" cols="40" rows="5" class="form-control" required id="id_content"></textarea> \
                {% csrf_token %} \
                <button type="submit" class="btn btn-warning btn-lg btn-block ">Submit</button> \
              </form></div></div>');

  }
  $(document).ready(function () {
    $('#myForm').trigger('reset')
  });


</script>
{%endblock%}

curriculum/templates/lesson_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-top: 3%;">
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <div class="card box-shadow-hover text-center">
                <div class="card-body" style="font-family: 'Source Code Pro', monospace;">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="submit" value="submit">
                        <a href="{% url 'curriculum:lesson-detail' subject_id=subject.id lesson_id=lesson.id %}"
                            class="btn btn-danger">Cancel</a>
                    </form>
                </div>

            </div>
           
        </div>
    </div>


    {% endblock %}