curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('',views.CourseListView,name='course_list'),
    path('<course_id>/', views.SubjectsView ,name='subjects-list'),
    path('<course_id>/lesson/<subject_id>/', views.LessonsView , name='lessons-list'),
    path('<course_id>/<subject_id>/add/', views.LessonCreateView,name='create'),
    path('subject/<subject_id>/<lesson_id>/',views.LessonDetailView,name='lesson-detail'),
    path('<subject_id>/<lesson_id>/update/',views.LessonUpdateView,name='lesson-update'),
    path('lesson/<int:pk>/delete/',views.LessonDeleteView.as_view(),name='lesson-delete'),
    path('1/api/courses/',views.CourseView.as_view()),
    path('1/api/subjects/',views.SubjectsApiView.as_view()),
    path('1/api/lessons/',views.LessonView.as_view()),
    path('1/<course_id>/payment/', views.payment, name='payment'),
    path('<course_id>/<order_id>/',views.Order),
    path('1/api/course_paid/',views.CoursePaidApiView.as_view()),

]

istudy_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('istudy_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

istudy_users/urls.py
from . import views
from django.urls import path,include

from .views import *
from rest_framework_simplejwt import views as jwt_views
from rest_framework.urlpatterns import format_suffix_patterns 
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('', views.index, name='index'),
    path('about/',views.about, name='about'),
    path('register/',views.register,name='signup'),
    path('user_login/',views.user_login,name='login'),
    path('user_logout/',views.user_logout,name='logout'),
    path('api/register/', views.registration_view, name='register'),
    path('users/',views.usersList.as_view()),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('profile/<username>/', views.profile, name='profile'),
    path('api/login/',LoginView.as_view()),


]

istudy_users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.utils import timezone
from cloudinary.models import CloudinaryField
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserManager(BaseUserManager):

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        if not username:
            raise ValueError(('The given username must be set'))
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False, ' ',
                                 **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        user = self._create_user(username, email, password, True, True,
                                 **extra_fields)
        user.is_active = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(max_length=250, unique=True)
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    
    
    parent = 'parent'
    student = 'student'
    teacher = 'teacher'
    
    roles=[
        ('parent','parent'),
        ('student','student'),
        ('teacher','teacher')
    ]
    role = models.CharField(max_length=200,choices=roles,default=student)
    phone_number=models.CharField(max_length=255,blank=True)
    full_name=models.CharField(max_length=255,blank=True)
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', ]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profile')
    bio = models.CharField(max_length=255,blank=True,default='My Bio')
    profile_picture = CloudinaryField('image',null=True,blank=True)

    
   
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    @classmethod
    def search_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()


    def __str__(self):
        return f'{self.user.username} Profile'

istudy_users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.forms import UserCreationForm
from cloudinary.forms import CloudinaryFileField
from django.contrib.auth import authenticate,login,logout

class UserForm(UserCreationForm):
    email = forms.EmailField(max_length=300,help_text='Required. Inform a valid email address')
  
    class Meta():
        model = User
        fields = ('full_name','username', 'email','role','phone_number','password1', 'password2',)

        labels ={
            'password1':'Password',
            'password2': 'Confirm Password',
        }

  
class UpdateUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('full_name','username', 'email','phone_number')


class UpdateUserProfileForm(forms.ModelForm):
    profile_picture = CloudinaryFileField(
     options = { 
      'tags': "directly_uploaded",
      'crop': 'limit', 'width': 1000, 'height': 1000,
      'eager': [{ 'crop': 'fill', 'width': 150, 'height': 100 }]
    })
    class Meta:

        model = Profile
        fields = [ 'profile_picture', 'bio']


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'id':'user-password'
            
            }
        )
    )
    # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username__iexact=username)
        if not qs.exists():
            raise forms.ValidationError('This is an invid user.')
        return username

class SignUpForm(UserCreationForm):
    full_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField(required=True)
    phone_number = forms.CharField()
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'id':'user-password'
            
            }
        )
    )
    password2 = forms.CharField(
        label = 'Confirm Password',

        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'id':'user-password'
            
            }
        )
    )
   
    class Meta():
        model = User
        fields = ('full_name','username', 'email','phone_number','role','password1', 'password2')
   

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username__iexact=username)
        if qs.exists():
            raise forms.ValidationError('This is an invalid username,please pick another.')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError('This email is already in use')
        return email

    

istudy_users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .forms import *
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view,permission_classes
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets
from rest_framework.generics import GenericAPIView
from .serialisers import *
from rest_framework import status
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated,IsAdminUser
from rest_framework.authtoken.models import Token
from .permissions import IsAdminOrReadOnly
from .email import send_welcome_email
from django.contrib import messages
from curriculum.models import Course
import jwt
from django.conf import settings
from django.contrib import auth


def index(request):
    courses = Course.objects.all()
    return render(request,'home.html',{"courses":courses})
def about(request):
    courses = Course.objects.all()
    return render(request,'about.html',{"courses":courses})    

def register(request):

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request,username = username,password = password)

            if user is not None:
                login(request,user)
            return redirect('/')
          
    else:
        form = UserForm()
    return render(request, 'registration/registration_form.html', {'form': form})


def user_login(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request,username=username,password=password)

        if user != None:
            login(request,user)
            return redirect('/')
        else:
            request.session['invalid_user'] = 1
    return render(request,'registration/login.html',{'form':form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

class usersList(APIView):
    permission_classes = (IsAdminUser,)
    def get(self,request):
        users = User.objects.all()
        serializer= UserDetailsSerializer(users,many=True)

        return Response(serializer.data)

@api_view(['POST',])
def registration_view(request):

    if request.method == 'POST':

        serializer = RegisterSerializer(data=request.data)
        data = {}

        if serializer.is_valid():
            user = serializer.save()
            data['response'] = 'successfully registered a new user.'
            data['email'] = user.email
            data['username'] = user.username
            data['full_name'] = user.full_name
            data['phone_number'] = user.phone_number


            token = Token.objects.get(user=user).key
            data['token'] = token

        else:
            data = serializer.errors
            print(data)
        return Response(data)


class LoginView(GenericAPIView):
    serializer_class = LoginSerializer

    def post(self, request):
        data = request.data
        username = data.get('username', '')
        password = data.get('password', '')
        user = auth.authenticate(username=username, password=password)

        if user:
            auth_token = jwt.encode(
                {'id':user.pk,'username': user.username,'email':user.email,'full_name':user.full_name,'phone_number':user.phone_number,'role':user.role}, settings.JWT_SECRET_KEY)

            serializer = UserDetailsSerializer(user)

            data = {'user': serializer.data, 'token': auth_token}

            return Response(data, status=status.HTTP_200_OK)

            # SEND RES
        return Response({'detail': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)



@login_required(login_url='login')
def profile(request, username):

    user = User.objects.get(username=username)
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateUserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateUserProfileForm(instance=request.user.profile)
    
    return render(request, 'registration/profile.html',{'user_form': user_form, 'profile_form': profile_form,})

istudy_users/templates/about.html
{% extends 'base.html'  %}
{% load static %}
{%block title %}About page{% endblock%}
{% block content %}

<main class="mt-3">
  <div class="container mt-5">
   

    <section class="text-center">
      <h2 class="mb-5 font-weight-bold" style="color:#76B947;font-family: 'Source Code Pro', monospace;">OUR GOAL</h2>
      <div class="row d-flex justify-content-center mb-4">
          <div class="col-md-8">
            <p class="grey-text">Enhance the quality of learning and teaching. Meet the learning style or needs of students. Improve the efficiency and effectiveness. Improve user-accessibility and time flexibility to engage learners in the learning process.</p>
          </div>
          <div class="row d-flex justify-content-center mb-3">
          {% for teacher in teachers %}
          <div class="card mb-3 mr-5 ml-3" style="max-width: 500px;">
            <div class="row no-gutters">
                      <div class="col-md-4">
                        <img src="{{teacher.profile_pic.url|default_if_none:'#'}}" class="card-img" alt="No image found">
                      </div>
                      <div class="col-md-8">
                        <div class="card-body">
                          <h5 class="card-title" style="color:#76B947;">{{teacher.user.username}}</h5>
                          <p class="card-text">{{teacher.bio|truncatechars:75}}</p>
                          <p class="card-text"><small class="text-muted"></small></p>
                        </div>
                      </div>
            </div>
            </div>
          {% endfor %}
          </div>
      </div>
    </section>

    <!-- <hr class="my-5" style="color:#76B947;"> -->
  </div>

<!-- section 3 for activities -->
<!--  -->
  <!-- <hr class="my-5" style="color:#76B947;"> -->
  <footer class="page-footer" style=" background: linear-gradient(45deg, #49D49D 10%, #5af0b1 90%);">
    <div class="container">
      <div class="row mt-4">
                <div class="col-md-4 mt-4">
                          <h3 class="text-center">About Us</h3> <br>
                          <p>We are a team of software developer for both web and mobile based softwares. For any consern or help needed, never hesitate to reach out to us, we are always there and ready for your service.</p>
                </div>
                <div class="col-md-3 mt-4 ml-5">
                          <h3>Our team:</h3>
                          <ul class="font-weight-bold">
                            <li>Cynthia</li>
                            <li>Benitha</li>
                            <li>K-Claudine</li>
                            <li>Odile</li>
                            <li>Rosine</li>
                            <li>M-Claudine</li>
                          </ul>
                </div>
                <div class="col-md-4 mt-4">
                          <h3>Contact Us</h3>
                          <ul>
                            <li>Address: Nyarugenge,Kigali,Rwanda</li>
                            <li>info.istudy@gmail.com</li>
                            <li>Phone: +250 781-234-567</li>
                          </ul>
                </div>
      </div>
      <div class="footer-copyright text-center py-3">
          <p>© Istudy 2021</p>
      </div>
    </div>
  </footer>

</main>


{%endblock%}

istudy_users/templates/home.html
{% extends './base.html'  %}
{% load static %}
{%block title %}index page{% endblock%}
{% block content %}
<div class="container-fluid " id="SLIDE_BG">
    <div  class="container-fluid d-flex align-items-center justify-content-center h-100">
      <div class="row d-flex justify-content-center text-center">
        <div class="col-md-10 text-white">
          <!-- heading -->
    <h2 class="display-4 font-weight-bold white-text  p-5 mb-2" style="color: #76B947;text-shadow: 2px 8px 6px rgba(0,0,0,0.2),0px -5px 35px rgba(255,255,255,0.3); font-family: 'Kranky', cursive; " > Istudy </h2>
  
          <!-- divider -->
          <hr style="color:#A2C7E5;">
  
          <!-- description -->
          <h4 class="white-text my-4 font-weight-bold" >Excellence through simplicity</h4>
          <a href="{% url 'curriculum:course_list' %}"> <button type="button" class="btn btn btn-outline-info text-uppercase" > Get Started</button> </a>
  
  
        </div>
      </div>
    </div>
  </div>
  <!--Image and mask-->
           
  
  
{% endblock %}

istudy_users/templates/navbar.html
    <nav class="navbar navbar-expand-md bg-light navbar-light" >
        <div class="container">
            <a class="navbar-brand mr-4  " href="/" style="color: #48a0e9; text-shadow: 2px 8px 6px rgba(0,0,0,0.2),0px -5px 35px rgba(255,255,255,0.3); font-family: 'Kranky', cursive; font-size: 30px; font-weight: bolder;">Istudy</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">

                <!-- Navbar Right Side -->
                {% if user.is_authenticated %}

                <div class="navbar-nav ml-auto" >
                    <a class="nav-item nav-link mx-3"  href="/">Home</a>
                    <li class="nav-item">
                        <a class="nav-link mx-3" 
                            href="{% url 'curriculum:course_list' %}">Curriculum</a>
                    </li>
                    {% if user.is_superuser %}
                    <li class="nav-item ">
                        <a class="nav-link mx-3"  href="{% url 'admin:index' %}">Admin</span> </a>
                    </li>
                    {% endif %}
                    <a class="nav-item nav-link mx-3"  href="{% url 'about' %}">About</a>
                    <a class="nav-item nav-link mx-3"  href="{% url 'profile' user.username %}">Profile</a>
                    <a class="nav-item nav-link mx-3"  href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <div class="navbar-nav ml-auto" >
                        <a class="nav-item nav-link mx-3 "  href="/">Home</a>

                        <a class="nav-item nav-link mx-3 " 
                            href="{% url 'curriculum:course_list' %}">Curriculum</a>
                        <a class="nav-item nav-link mx-3"  href="{% url 'about' %}">About</a>
                        <a class="nav-item nav-link mx-3"  href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link mx-3"  href="{% url 'signup' %}">Register</a>
                    </div>

                </div>
                {% endif %}

            </div>
        </div>
    </nav>